### ISSUE TITLE
Does not give option to enable

### ISSUE THREAD

**Issue by knuckleheader** [juliang22/ObsidianYoutubeTimestampNotes#1]
Hi I have placed the folder correctly in the plugins folder.  However I have no option to enable the plugin.

![image](https://user-images.githubusercontent.com/48196950/168662891-18d6bf4a-69ee-4d5d-91b2-102ec949e6ee.png)

I am unsure what I am doing wrong?  Thanks for your help! I really want to try this plugin, it provides one of the functions I miss most about roam.

**Comment by juliang22** [comment]
Thanks for this! Fixed a bug with the data.json not being loaded and bundled in the main.js file so people can use the plugin without running "npm run dev." Try cloning the repo again and it should be fully functional!
