### ISSUE TITLE
Invalid Video URL, weird paste behaviour 

### ISSUE THREAD

**Issue by otokhorkheli** [juliang22/ObsidianYoutubeTimestampNotes#55]
Hello,

After enabling the Timestamp Community plugin in Obsidian my default paste behavior has changed.

When I use ctrl+v it's always pasting 

"> [!error] Invalid Video URL
> The highlighted link is not a valid video URL. Please try again with a valid link."

This, no matter what I'm trying to paste is just string, YouTube URL, etc.

The solution I found is to use ctrl+shift+v which works for me to paste texts or URLs.

To use the plugin itself I'm manually creating a code block
```
```timestamp-url
YOUTUBE_URL
```
```

**Comment by otokhorkheli** [comment]
There was a conflict with other plugin

**Comment by Dennyyusuf** [comment]
which plugin?
